language: php

php:
  - 5.6
  - 7.0

install:
  - composer require satooshi/php-coveralls:~0.6@stable

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

env:
 global:
   - setup=basic
   - APP_ENV=production
   - APP_DEBUG=true
   - DB_DATABASE=cp3
   - DB_HOST=localhost
   - DB_USERNAME=homestead
   - DB_PASSWORD=secret
   - DRIVER=mysql
   - JWT-KEY=12345

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'