language: php

php:
  - 5.6
  - 7.0

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

env:
 global:
   - setup=basic
   - APP_ENV=production
   - APP_DEBUG=true
   - DB_DATABASE=cp3
   - DB_HOST=localhost
   - DB_USERNAME=homestead
   - DB_PASSWORD=secret
   - DRIVER=mysql
   - JWT-KEY=12345

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v